name: Release Please

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies for Firebase functions
        run: npm install
        working-directory: firebase/functions

      - name: Run Release Please for Firebase functions
        uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: firebase/functions
          path: firebase/functions

      - name: Install dependencies for web
        run: npm install
        working-directory: web

      - name: Run Release Please for web
        uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: web
          path: web
